stages:
  - plan
  - apply

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

variables:
  TERRAFORM_DIR: ./terraform
  TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_PRO

plan:
  stage: plan
  resource_group: terraform
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: apply
  resource_group: terraform
  script:
    - terraform -chdir=${TF_ROOT} init
    - terraform -chdir=${TF_ROOT} apply plan.cache
  only:
    - main
