workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - plan
  - apply

image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

variables:
  TERRAFORM_DIR: ./terraform
  GITLAB_TOKEN: $GITLAB_AUTOMATION_TOKEN
  TF_VAR_azure_subscription: $AZURE_SUBSCRIPTION_PRO

# checkov:
#   stage: plan
#   image: bridgecrew/checkov:latest
#   script:
#     - checkov -d ${TERRAFORM_DIR} --quiet --output json > checkov_report.json
#   artifacts:
#     name: checkov_report
#     paths:
#       - checkov_report.json
#     reports:
#       checkov: checkov_report.json

plan:
  stage: plan
  resource_group: terraform
  script:
    - terraform -chdir=${TERRAFORM_DIR} init
    - terraform -chdir=${TERRAFORM_DIR} plan -out=planfile
  artifacts:
    name: plan
    paths:
      - ${TERRAFORM_DIR}/planfile

apply:
  stage: apply
  resource_group: terraform
  script:
    - terraform -chdir=${TERRAFORM_DIR} init
    - terraform -chdir=${TERRAFORM_DIR} apply planfile
  only:
    - main
